# This script deploys your website automatically
name: CD

# Only trigger this script when you push to the master branch
on:
  push:
    branches: [ master ]

# Specify the tasks to run when this script gets triggered
jobs:
  build:
    runs-on: ubuntu-latest

    # Download our master branch
    steps:
    - uses: actions/checkout@v2
    - name: Install modules
      run: npm install

    # Configure Git Identity
    - name: Configure Git Identity
      run: git config --global user.email "deany.y.ca@gmail.com" && git config --global user.name "nekopudding"
    # Run our deployment command
    - name: Deploying the static website to gh-pages
      run: npm run deploy